name: build
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Get the latest CMake and Ninja
        uses: lukka/get-cmake@latest
      - name: Run CMake with Ninja
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          buildDirectory: '${{ github.workspace }}/build'
          buildWithCMakeArgs: '-- -v'
          cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE="Release" -DCMAKE_C_FLAGS="-s"'
      - name: Copy the files to the release directory
        run: mkdir release && cp LICENSE *.rules *.service build/interceptkb release/
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: interceptkb-amd64-${{ steps.slug.outputs.sha7 }}
          path: release
